### ISSUE TITLE
Empty gcode file

### ISSUE THREAD

**Issue by makenb** [utlco/tcnc#6]
Hi, @utlco 

I just downloaded this software today to test, It seams like it would be perfect for my needs.
I have a home made plotter with a drag knife running grbl. however for some reason the gcode files 
just contain a header and footer with no paths. the header says there are 92 paths, but no gcode is written... if I activate the "show tcnc path" Layer in inkscape it is also empty. and if I activate the log file it is not written. I'm on ubuntu 15.04 and inkscape 0.91

Thanks,
Maken

**Comment by utlco** [comment]
Hi Maken,
Can you attach a sample Inkscape SVG file and the gcode output for which this happens?
I'm using a Mac and I haven't tested tcnc with Linux yet so maybe that's an issue.
thanks,
- Claude

**Comment by makenb** [comment]
@utlco,
Here is the file:

[Snowflake.svg.zip](https://github.com/utlco/tcnc/files/645051/Snowflake.svg.zip)

And here is the resultant gcode:

[snowflake2_0001 .ngc.txt](https://github.com/utlco/tcnc/files/645055/snowflake2_0001.ngc.txt)

Thanks,
Maken

**Comment by utlco** [comment]
Thanks for the files.
I can't seem to reproduce your bug so I'll need more information. I've checked in some changes that include writing out the values of all the options in the gcode header.
You should also turn off the tangent tool preview layer which can take up a lot of memory if your paths are complex. The tool path preview layer will still be created.
Could you try it again with the latest version and send me the output file again?
Also could you let me know how much memory your machine has?
thanks,
- Claude

PS. Also, it would be helpful if you could let me know if it works at all with a simpler drawing.

**Comment by makenb** [comment]
[teststar.ngc.zip](https://github.com/utlco/tcnc/files/650787/teststar.ngc.zip)
@utlco 
Hi Claude,
Sorry for lag. I was finally able to try your new code, however I dont see any difference. I ve included the output file below. I also try a file with just a circle same output but it was much quicker, the more complex file takes a long time so I think its doing something just not able to write it to the output. My computer has an i7 quadcore and 8 gigs of ram.

Thanks,
Maken

**Comment by utlco** [comment]
Hi Maken,

The lack of option values in the header of the file teststar.ngc indicates
a slightly out of date version of tcnc. Could you update with the latest
from the github repository and send me the output again?
The latest should output the values of all the command line options in the
header, which will make it much easier to figure out the problem.
I really appreciate you help in testing!

thanks,
- Claude

**Comment by makenb** [comment]
@utlco,
I must have copied the wrong files before, here is the new one

Maken

[teststar.ngc.zip](https://github.com/utlco/tcnc/files/653628/teststar.ngc.zip)

**Comment by utlco** [comment]
Could you send me the SVG source file as well? - thanks

**Comment by makenb** [comment]
Its the same i posted before. Maybe ill try to use it on command line tonight.

**Comment by utlco** [comment]
Aha, I found the problem. Your final Z cut depth is > 0 which would
normally mean the tool never reaches the material surface (which is usually
at Z == 0). Tcnc won't produce any G code for this situation, which is a
bug...
I'll fix this

**Comment by makenb** [comment]
Oh ill try to change that and see. I didnt set it because my machine has no z axis i just use spindle to activate.
Thanks, 
Maken
