### ISSUE TITLE
Command line tcnc usage

### ISSUE THREAD

**Issue by giantstonex7** [utlco/tcnc#8]
Hi, I'm trying to figure out how to use tcnc as a command line tool to generate g-code for my tangent knife cnc. I have a set of arcs in the format ( center, radius, start angle, end angle), and I can use dxfwrite to export the arcs as dxf files. I can then use the Inkscape GUI and tcnc to create the g-code, but I hope be able to do it in the command line. 

I read some of the python scripts, and get lost a bit.

**Comment by giantstonex7** [comment]
an example like https://github.com/onyxfish/svg2g/blob/master/test.sh would be great, 
which is another inkscape extension that supports command line usage.

**Comment by utlco** [comment]
Something like this should work:

```
#!/bin/sh

# This would be the path to where tcnc.py is installed
TCNC_PATH=../tcnc

# Your python executable (Python 2.7 is currently required)
PYTHON_BIN=/usr/bin/python

PYTHONPATH="$PYTHONPATH:$TCNC_PATH"

# Some example tcnc settings. More can be passed via the command line...
TCNC_OPTIONS="--gcode-units=mm --z-safe=.5 --output-path=./gcode.ngc"

# Suppress the path preview SVG output by redirecting stdout to /dev/null
$PYTHON_BIN $TCNC_PATH/tcnc.py $TCNC_OPTIONS $@ >/dev/null
```

**Comment by giantstonex7** [comment]
i tried the following script:

#!/bin/sh

# This would be the path to where tcnc.py is installed
TCNC_PATH=/home/sam/tcnc-master/tcnc

# Your python executable (Python 2.7 is currently required)
PYTHON_BIN=/usr/bin/python

PYTHONPATH="$PYTHONPATH:$TCNC_PATH"

# Some example tcnc settings. More can be passed via the command line...
TCNC_OPTIONS="--gcode-units=mm --path-smooth-fillet=True --a-feed=1000  --xy-feed=2000 --z-feed=400 --z-safe=0 --z-depth=8 --z-step=8 /home/sam/catkin_ws/src/fur_processing/scripts/collar_cutting/1s.svg --output-path=~/NGC_files/tcnc_gcode.ngc"

# Suppress the path preview SVG output by redirecting stdout to /dev/null
$PYTHON_BIN $TCNC_PATH/tcnc.py $TCNC_OPTIONS $@ >/dev/null

and the program kept running, until i press ctrl+c, it generated 600+mb ngc file. 

this is the command line output:
./tcnc_commandline_usage.sh 

^CTraceback (most recent call last):
  File "/home/sam/tcnc-master/tcnc/tcnc.py", line 417, in <module>
    debug_layer_name='tcnc debug')
  File "/home/sam/tcnc-master/tcnc/inkscape/inkext.py", line 201, in main
    self.run()
  File "/home/sam/tcnc-master/tcnc/tcnc.py", line 235, in run
    cam.generate_gcode(path_list)
  File "/home/sam/tcnc-master/tcnc/cam/simplecam.py", line 177, in generate_gcode
    self.generate_segment_gcode(segment, tool_depth)
  File "/home/sam/tcnc-master/tcnc/cam/simplecam.py", line 494, in generate_segment_gcode
    self.feed_distance += segment.length()
  File "/home/sam/tcnc-master/tcnc/geom/arc.py", line 199, in length
    return abs(self.radius * self.angle)
  File "/home/sam/tcnc-master/tcnc/geom/arc.py", line 172, in radius
    @property
KeyboardInterrupt
